### ISSUE TITLE
My character remains visible.

### ISSUE THREAD

**Issue by SarahSoulless** [Silverfeelin/LuAnimator#1]
;-; i did everything.. but when i go ingame i see me without any animations and my thing with animation

**Comment by Silverfeelin** [comment]
This is not nearly enough information for me to help you. What have you
tried? Are there any steps that you feel you may have done wrong?

I don't really see this as being an issue with the tool as much as it's an
issue with you setting everything up. I'd love to help but I need more
information to be able to!

**Comment by SarahSoulless** [comment]
Okay Senpai Silverfeelin..
I did every step, with LuAnimator and DrawablesGenerator..
but when i go ingame and got the Item in my hand i have my Animation there, but my Character is there too but without animation, because i did a Cat with the LuAnimator and Drawables, but there is the Cat with Animation and Me Without, like im just standing there.

**Comment by Silverfeelin** [comment]
Did you put the output of the LuAnimator (the code) in the luanimation.lua file in your mod? Did you bind the `LuAnimator - Animate` key in your controls?

It might be better for you to zip and share your mod and the canvas (generated blank image) you're using and send it to me at Silverfeelin@gmail.com. Otherwise, I'll just be stuck guessing here.

**Comment by RocketSlimer** [comment]
I have what I think is the same issue. The animations work and all, but my player is still visible behind it.
http://image.prntscr.com/image/a356dba8206d40c38557ccc71cf44b41.png

**Comment by Silverfeelin** [comment]
_That_ is not an issue with the tool/mod.
I can't think of a method that is reliable enough to make the tech do this; it'd revolve around making assumptions based on the entity portrait of the character. There's also the possibility of animations where you wouldn't want your character to be invisible (although you'd most likely want to manually disable the 'fly' state at that point too).

You are to make your character invisible yourself.
I might add a guide to the Wiki soon. For now, you can see my post on the forums here: http://community.playstarbound.com/threads/luanimator.109868/#post-3013276

Looking back at it, it seems I misunderstood SarahSoulless; I thought Sarah meant only their character appeared, not the animation. Sorry about that. Hope this helps!

**Comment by RocketSlimer** [comment]
Thanks. I've fixed it now.

**Comment by SarahSoulless** [comment]
Thanks Senpai Silver!

**Comment by SarahSoulless** [comment]
Im acually confused now.. i did everything in the link, but the Batch Files already had the correct path, so i just did the shortcut thingie.. but it doesnt do anyhing ;-;

**Comment by Silverfeelin** [comment]
SarahSoulless, did you follow the video? It will show you what to do after setting up the batch files.

**Comment by SarahSoulless** [comment]
I cant even Edit that.. it just opens the Batchfile and there is stuff in it, nothing more.

**Comment by Silverfeelin** [comment]
You need to open the file in a text editor. Try opening the file inside
Notepad or Notepad++.
After correcting the path so it matches the path to your files, follow the video.
If the file doesn't do anything after dragging a player file on top of it, it probably means the path is invalid.

**Comment by SarahSoulless** [comment]
set "str=%1%.json"
"D:\Steam\steamapps\common\Starbound\win32\dump_versioned_json.exe" %1 %str%
PAUSE

set str=%1
set str=%str:~0,-5%
"D:\Steam\steamapps\common\Starbound\win32\make_versioned_json.exe" %1 %str%
PAUSE

thats what they both have in it.. from the start i downloaded them

**Comment by Silverfeelin** [comment]
So your Starbound is installed in D:\Steam\steamapps\common\Starbound? Then it should create a JSON file in your player folder after dragging your player file on top of the dump batch file (making sure it says open with). Does the batch file show any errors?

**Comment by SarahSoulless** [comment]
No my starbound is in program (x86)\steam\steamapps\common\Starbound ;-;

**Comment by Silverfeelin** [comment]
Well there's your problem. You need to change the file path in both files so that they form absolute paths to the executables (the .exe files).

The paths in the given batch files are correct for my computer, but since you have Starbound installed elsewhere you need to change it.
Make sure the paths match exactly. I recommend going to the folder then copy and pasting the path from your address bar.

**Comment by SarahSoulless** [comment]
Now i got my path, but still nothing is happening..
there is a long text but it just says my path over and over...

**Comment by Silverfeelin** [comment]
It didn't create a .json file matching the file name of the player file you dragged on top of it? The JSON file should be listed in the same folder as the original player file.

**Comment by SarahSoulless** [comment]
i dragged the player thingie like in the video on it, and it open the batch file, it doesnt closes it instantly.. and then there is  a is my path over and over again ..

**Comment by Silverfeelin** [comment]
It doesn't close instantly because the last line if the batch file says PAUSE. You should be able to press any key to close that window when it stops doing anything. The JSON file should be generated though.

**Comment by SarahSoulless** [comment]
It doesnt create the JSON file though... and i even pressed a key it just closes and does nothing ;-;

**Comment by Silverfeelin** [comment]
Mind continuing this through Steam? I can't help but think you simply misconfigured something, and working like this doesn't seem to help us resolve the issue.
My Steam name is "Silverfeelin".

**Comment by Silverfeelin** [comment]
Solved. There was an issue with SarahSoulless' dump executable preventing the batch from working.
