### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by BananaNomNom** [Silverfeelin/LuAnimator#2]
Hey I was recently on your hatter website and this seemed the only way to contact you. i was having trouble enabling the over 86x86 restrictions. Any help would be apreciated.

**Comment by Silverfeelin** [comment]
This section is meant for issues regarding the LuAnimator.  
The footer of the Hatter page (or any other page on the site, really) lists ways to contact me. I recommend emailing me at Silverfeelin@gmail.com if the below does not work.

To bypass the restriction, first open the console of your browser. For most browsers this is done by pressing `F12`.
After opening the console, you should be able to input code. If not, make sure you have the console tab selected.
Enter the line `avoidRestrictions = true;` and press enter. Most browsers will print `true` as a result on a new line.
After this you should be able to select an image larger than 85x85 pixels. If it still prevents you from doing so, refresh the page and try again. You may also need to keep your console open while using the Hatter with this bypass.

![](http://i.imgur.com/ufqLpUK.png)
